version: '3'

services:

  php-cli:
    image: 'thecodingmachine/php:7.2-v1-cli'
    volumes:
      - './:/usr/src/app:delegated'
    environment:
      PHP_EXTENSIONS: bcmath

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

